
package org.oc.ws.client.marcas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaMarcasImplWSService", targetNamespace = "http://marca.ws.oc.org/", wsdlLocation = "http://localhost:8087/getMarcasWS?wsdl")
public class ConsultaMarcasImplWSService
    extends Service
{

    private final static URL CONSULTAMARCASIMPLWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAMARCASIMPLWSSERVICE_EXCEPTION;
    private final static QName CONSULTAMARCASIMPLWSSERVICE_QNAME = new QName("http://marca.ws.oc.org/", "ConsultaMarcasImplWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/getMarcasWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAMARCASIMPLWSSERVICE_WSDL_LOCATION = url;
        CONSULTAMARCASIMPLWSSERVICE_EXCEPTION = e;
    }

    public ConsultaMarcasImplWSService() {
        super(__getWsdlLocation(), CONSULTAMARCASIMPLWSSERVICE_QNAME);
    }

    public ConsultaMarcasImplWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAMARCASIMPLWSSERVICE_QNAME, features);
    }

    public ConsultaMarcasImplWSService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAMARCASIMPLWSSERVICE_QNAME);
    }

    public ConsultaMarcasImplWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAMARCASIMPLWSSERVICE_QNAME, features);
    }

    public ConsultaMarcasImplWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaMarcasImplWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConsultaMarcasWS
     */
    @WebEndpoint(name = "ConsultaMarcasImplWSPort")
    public IConsultaMarcasWS getConsultaMarcasImplWSPort() {
        return super.getPort(new QName("http://marca.ws.oc.org/", "ConsultaMarcasImplWSPort"), IConsultaMarcasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaMarcasWS
     */
    @WebEndpoint(name = "ConsultaMarcasImplWSPort")
    public IConsultaMarcasWS getConsultaMarcasImplWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://marca.ws.oc.org/", "ConsultaMarcasImplWSPort"), IConsultaMarcasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAMARCASIMPLWSSERVICE_EXCEPTION!= null) {
            throw CONSULTAMARCASIMPLWSSERVICE_EXCEPTION;
        }
        return CONSULTAMARCASIMPLWSSERVICE_WSDL_LOCATION;
    }

}
