
package org.oc.ws.client.marcas;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IConsultaMarcasWS", targetNamespace = "http://marca.ws.oc.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConsultaMarcasWS {


    /**
     * 
     * @return
     *     returns org.oc.ws.client.marcas.MarcaType
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMarcas", targetNamespace = "http://marca.ws.oc.org/", className = "org.oc.ws.client.marcas.GetAllMarcas")
    @ResponseWrapper(localName = "getAllMarcasResponse", targetNamespace = "http://marca.ws.oc.org/", className = "org.oc.ws.client.marcas.GetAllMarcasResponse")
    public MarcaType getAllMarcas();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "teste", targetNamespace = "http://marca.ws.oc.org/", className = "org.oc.ws.client.marcas.Teste")
    @ResponseWrapper(localName = "testeResponse", targetNamespace = "http://marca.ws.oc.org/", className = "org.oc.ws.client.marcas.TesteResponse")
    public String teste();

}
